### ISSUE TITLE
Come up with a different name/product instead of Lego

### ISSUE THREAD

**Issue by NinniS** [s02blom/LegoWebStore#3]
Lego and its iconic components are trademarked. We need to come up with a different name for what we are selling on our web store.

**Comment by Uplink036** [comment]
Here are some suggestions:
- L3go
- Duplo 
- Triplex
- Buildables
- SnapStructs (patent pending)

**Comment by s02blom** [comment]
Add a disclaimer or similar that we do not intend any copyright infrignment

**Comment by s02blom** [comment]
Disclaimer has been added in accordance with the LEGO GROUP own advice, see their [Fair Play](https://www.lego.com/en-us/legal/notices-and-policies/fair-play/?locale=en-us).
